In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Past In and Out.csv')

In [3]:
from datetime import datetime
def Milli(X):
    given_date_time = X
    epoch = datetime(1970, 1, 1)
    time_difference = given_date_time - epoch
    total_seconds = time_difference.total_seconds()
    milliseconds = int(total_seconds * 1000)
    return milliseconds

def Date_Time(X):
    seconds = X / 1000
    date_time = datetime.fromtimestamp(seconds)
    date_time1= date_time.strftime('%d-%m-%y %H:%M:%S')
    return date_time1

In [4]:
from datetime import datetime
import pandas as pd
IN_Time=[]
OUT_Time=[]

for i in range(df.shape[0]):
    x1 = datetime.strptime(df['IN_TIME'][i], '%d-%m-%y %H:%M:%S')
    x1m = Milli(x1)
    IN_Time.append(x1m)
    y1 = datetime.strptime(df['OUT_TIME'][i], '%d-%m-%y %H:%M:%S')
    y1m = Milli(y1)
    IN_Time.append(x1m)
    OUT_Time.append(y1m)
In = pd.DataFrame(IN_Time)
Out = pd.DataFrame(OUT_Time)

In [5]:
df.drop(columns='REF_ID',axis=1,inplace=True)
df.drop(columns='VALIDITY',axis=1,inplace=True)
df.drop(columns='CON_NUM',axis=1,inplace=True)
df.drop(columns='IN_TIME',axis=1,inplace=True)
df.drop(columns='OUT_TIME',axis=1,inplace=True)

In [6]:
df['In_time'] = In
df['Out_time'] = Out

In [7]:
df.dropna(axis=0,inplace=True)

In [8]:
df.reset_index(inplace=True)

In [9]:
df1=pd.get_dummies(data=df['STATUS'],drop_first=True)
df['L']=df1

In [10]:
df.drop(columns='STATUS',axis=1,inplace=True)
df.drop(columns='index',axis=1,inplace=True)

In [11]:
Time_diff = []
for i in range(df.shape[0]):
    Time_diff.append(df['Out_time'][i]-df['In_time'][i])
    
df['Time_Diff'] = Time_diff
def find_outliers(df,col):
    q1=df[col].quantile(0.25)
    q3=df[col].quantile(0.75)
    IQR=q3-q1
    lv=q1-1.5*IQR
    hv=q3+1.5*IQR
    df=df[(df[col]<=hv) | (df[col]>=lv)]
    return df
find_outliers(df,'Time_Diff')

       CON_SIZE        In_time       Out_time  L    Time_Diff
0          40.0  1668216594000  1675732992000  0   7516398000
1          40.0  1668216594000  1675366422000  0   7149828000
2          20.0  1669124439000  1676005749000  0   6881310000
3          20.0  1669124439000  1677572528000  0   8448089000
4          20.0  1670173982000  1681752196000  0  11578214000
...         ...            ...            ... ..          ...
24524      40.0  1678738917000  1682467275000  1   3728358000
24525      40.0  1678738917000  1682478340000  1   3739423000
24526      20.0  1678738917000  1682474490000  1   3735573000
24527      40.0  1678740230000  1682488202000  0   3747972000
24528      40.0  1678740230000  1682464069000  1   3723839000

[24529 rows x 5 columns]

In [12]:
df.drop(columns='Time_Diff',axis=1,inplace=True)

In [13]:
x=df.drop('Out_time',axis=1)
y=df['Out_time']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(19623, 3)
(4906, 3)
(19623,)
(4906,)

In [14]:
import numpy 
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

print(lr.coef_)
print(lr.intercept_)

[2.58619498e+06 1.84151937e+00 1.46778791e+08]
-1409148897269.0027

In [15]:
y_pred=lr.predict(x_test)
print(y_pred)
print(y_test)

[1.68175294e+12 1.68044246e+12 1.68091108e+12 ... 1.68220033e+12
 1.67711545e+12 1.67787852e+12]
20997    1681911443000
12655    1679226166000
19424    1681999096000
16029    1681056131000
9602     1678633379000
             ...
3244     1675876990000
3877     1676609170000
23117    1682557658000
7149     1677308338000
5655     1677050680000
Name: Out_time, Length: 4906, dtype: int64

In [16]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_pred,y_test)
mse

1.257241066359832e+18

In [17]:
df=pd.read_csv('Insert data.csv')
x = df['IN_TIME'][0]
x1 = datetime.strptime(x, '%d-%m-%y %H:%M:%S')
x1m=Milli(x1)
Out=[[40,x1m,1]]
x1=lr.predict(Out)
Outtime = datetime.strptime(Date_Time(int(x1)),'%d-%m-%y %H:%M:%S')
print(Outtime)

2021-06-25 07:24:57

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [18]:
x1 = datetime.strptime(Date_Time(int(x1)),'%d-%m-%y %H:%M:%S')

In [19]:
print(Outtime==Outtime)

True

In [20]:
df = pd.read_csv('Insert data.csv')

In [22]:
df

,ID,IN_TIME,REF_ID,CON_NUM,CON_SIZE,STATUS
0,322,14-03-22 15:46:44,ALO11887,SPRE0057868,20,L
1,322,14-03-22 15:46:44,ALO11887,ANKJ1447873,20,L
2,322,14-03-22 15:46:44,ALO11887,ACLU3053768,20,L
3,326,17-04-22 04:41:42,DP02MAR10,BUDE0578181,40,L
4,326,17-04-22 04:41:42,DP02MAR10,UPDU1678037,20,E
...,...,...,...,...,...,...
345,554,20-03-22 14:48:13,ALO11980-98997-330244,IVIP5581378,20,L
346,555,20-03-22 14:48:13,ALO11980-98998-330245,XEFF1829672,20,L
347,556,20-03-22 14:48:13,ALO11980-98999-330246,BFIU2996554,20,L
348,557,20-03-22 14:48:13,ALO11980-99000-330247,RDCW7179253,20,L
349,558,20-03-22 14:48:13,ALO11980-99001-330248,NUDE0749531,20,L

In [23]:
OutTime=[]
s=0
for i in range(df.shape[0]):
    if df['STATUS'][i] == 'L':
        s=1
    else:
        s=0
    pre = Predict_Out_Time(df['IN_TIME'],df['CON_SIZE'],s)
    OutTime.append(pre)

NameError: name 'Predict_Out_Time' is not defined

In [26]:
type(df['IN_TIME'][0])

str

In [27]:
import numpy
import pandas as pd
from datetime import datetime
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


def Predict_Out_Time(Time,size,state):
    df = pd.read_csv('Past In and Out.csv')

    def Milli(X):
        given_date_time = X
        epoch = datetime(1970, 1, 1)
        time_difference = given_date_time - epoch
        total_seconds = time_difference.total_seconds()
        milliseconds = int(total_seconds * 1000)
        return milliseconds

    def Date_Time(X):
        seconds = X / 1000
        date_time = datetime.fromtimestamp(seconds)
        date_time1= date_time.strftime('%d-%m-%y %H:%M:%S')
        return date_time1

    IN_Time = []
    OUT_Time = []
    for i in range(df.shape[0]):
        x1 = datetime.strptime(df['IN_TIME'][i], '%d-%m-%y %H:%M:%S')
        x1m = Milli(x1)
        IN_Time.append(x1m)
        y1 = datetime.strptime(df['OUT_TIME'][i], '%d-%m-%y %H:%M:%S')
        y1m = Milli(y1)
        IN_Time.append(x1m)
        OUT_Time.append(y1m)
    In = pd.DataFrame(IN_Time)
    Out = pd.DataFrame(OUT_Time)
    df.drop(columns='REF_ID', axis=1, inplace=True)
    df.drop(columns='VALIDITY', axis=1, inplace=True)
    df.drop(columns='CON_NUM', axis=1, inplace=True)
    df.drop(columns='IN_TIME', axis=1, inplace=True)
    df.drop(columns='OUT_TIME', axis=1, inplace=True)
    df['In_time'] = In
    df['Out_time'] = Out
    df.dropna(axis=0, inplace=True)
    df.reset_index(inplace=True)
    df1 = pd.get_dummies(data=df['STATUS'], drop_first=True)
    df['L'] = df1
    df.drop(['STATUS'], axis=1, inplace=True)
    df.drop(columns='index',axis=1,inplace=True)
    Time_diff = []
    for i in range(df.shape[0]):
        Time_diff.append(df['Out_time'][i]-df['In_time'][i])
        
    df['Time_Diff'] = Time_diff
    def find_outliers(df,col):
        q1=df[col].quantile(0.25)
        q3=df[col].quantile(0.75)
        IQR=q3-q1
        lv=q1-1.5*IQR
        hv=q3+1.5*IQR
        df=df[(df[col]<=hv) | (df[col]>=lv)]
        return df
    find_outliers(df,'Time_Diff')
    df.drop(columns='Time_Diff',axis=1,inplace=True)
    x = df.drop('Out_time', axis=1)
    y = df['Out_time']
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
    # print(x_train.shape)
    # print(x_test.shape)
    # print(y_train.shape)
    # print(y_test.shape)
    lr = LinearRegression()
    lr.fit(x_train, y_train)
    # print(lr.coef_)
    # print(lr.intercept_)
    y_pred = lr.predict(x_test)
    # print(y_pred)
    # print(y_test)
    mse = mean_squared_error(y_pred, y_test)
    # mse
    df = pd.read_csv('Insert data.csv')
    x = Time
    x1 = datetime.strptime(x, '%d-%m-%y %H:%M:%S')
    x1m = Milli(x1)
    Out = [[size, x1m, state]]
    x1=lr.predict(Out)
    Outtime = datetime.strptime(Date_Time(int(x1)),'%d-%m-%y %H:%M:%S')
    return Outtime


pre = Predict_Out_Time('14-03-22 15:46:44',20,1)
print(pre)

df = pd.read_csv('Insert data.csv')
OutTime=[]
s=0
for i in range(df.shape[0]):
    if df['STATUS'][i] == 'L':
        s=1
    else:
        s=0
    pre = Predict_Out_Time(df['IN_TIME'][i],df['CON_SIZE'][i],s)
    OutTime.append(pre)
print(OutTime)
df['Out_Time'] = OutTime

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

2021-06-24 17:02:53

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

[datetime.datetime(2021, 6, 24, 17, 2, 53), datetime.datetime(2021, 6, 24, 17, 2, 53), datetime.datetime(2021, 6, 24, 17, 2, 53), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 25, 11, 19), datetime.datetime(2021, 8, 25, 11, 19), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 1, 2, 24), datetime.datetime(2021, 6, 27, 1, 43, 55), datetime.datetime(2021, 6, 27, 2, 22, 48), datetime.datetime(2021, 6, 24, 20, 25, 10), datetime.datetime(2021, 6, 24, 20, 49, 7), datetime.datetime(2021, 6, 27, 8, 45, 41), datetime.datetime(2021, 6, 27, 8, 45, 41), datetime.datetime(2021, 6, 27, 11, 53, 4), datetime.datetime(2021, 6, 27, 11, 53, 4), datetime.datetime(2021, 6, 27, 22, 36, 18), datetime.datetime(2021, 6, 27, 22, 54, 30), datetime.datetime(2021, 6, 28, 0, 6, 23), datetime.datetime(2021, 6, 29, 21, 36, 8), datetime.datetime(2021, 6, 29, 21, 36, 8), datetime.datetime(2021, 6, 29, 21, 57, 8), datetime.datetime(2021, 6, 29, 22, 40, 20), datetime.datetime(2021, 6, 29, 22, 45, 41), datetime.datetime(2021, 6, 29, 22, 57, 50), datetime.datetime(2021, 6, 29, 23, 10, 36), datetime.datetime(2021, 6, 29, 23, 56, 46), datetime.datetime(2021, 6, 29, 23, 56, 46), datetime.datetime(2021, 6, 30, 4, 53, 27), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 7, 1, 16, 12, 28), datetime.datetime(2021, 7, 1, 16, 16, 15), datetime.datetime(2021, 7, 1, 1, 59, 13), datetime.datetime(2021, 7, 1, 3, 7, 12), datetime.datetime(2021, 7, 2, 1, 45, 11), datetime.datetime(2021, 7, 2, 1, 45, 11), datetime.datetime(2021, 7, 2, 4, 16, 11), datetime.datetime(2021, 6, 30, 13, 5, 42), datetime.datetime(2021, 6, 26, 20, 8, 38), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 26, 20, 8, 38), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 3, 39, 29), datetime.datetime(2021, 7, 2, 3, 39, 29), datetime.datetime(2021, 7, 2, 3, 39, 29), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 20, 40, 15), datetime.datetime(2021, 7, 2, 21, 59, 4), datetime.datetime(2021, 7, 2, 22, 26, 26), datetime.datetime(2021, 7, 3, 14, 0, 17), datetime.datetime(2021, 7, 3, 14, 0, 17), datetime.datetime(2021, 7, 3, 14, 24, 41), datetime.datetime(2021, 7, 3, 14, 27, 53), datetime.datetime(2021, 7, 3, 2, 57, 47), datetime.datetime(2021, 7, 4, 2, 20, 11), datetime.datetime(2021, 7, 4, 4, 48, 7), datetime.datetime(2021, 7, 4, 5, 18, 17), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 36, 58), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 4, 8, 16, 8), datetime.datetime(2021, 7, 4, 11, 39, 11), datetime.datetime(2021, 7, 5, 4, 13, 56), datetime.datetime(2021, 7, 5, 4, 25, 41), datetime.datetime(2021, 7, 5, 5, 4, 11), datetime.datetime(2021, 7, 5, 5, 16), datetime.datetime(2021, 7, 5, 5, 16), datetime.datetime(2021, 7, 4, 15, 19, 17), datetime.datetime(2021, 7, 4, 15, 28, 55), datetime.datetime(2021, 7, 4, 16, 16, 59), datetime.datetime(2021, 7, 4, 16, 16, 59), datetime.datetime(2021, 7, 5, 6, 52, 16), datetime.datetime(2021, 7, 5, 7, 0, 37), datetime.datetime(2021, 7, 4, 18, 4), datetime.datetime(2021, 7, 4, 18, 17, 7), datetime.datetime(2021, 7, 4, 18, 23, 52), datetime.datetime(2021, 7, 4, 18, 50, 56), datetime.datetime(2021, 7, 5, 9, 31, 25), datetime.datetime(2021, 7, 5, 10, 8, 2), datetime.datetime(2021, 7, 4, 21, 16, 8), datetime.datetime(2021, 7, 5, 12, 45, 53), datetime.datetime(2021, 7, 5, 14, 16, 38), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 44, 28), datetime.datetime(2021, 7, 5, 15, 56, 20), datetime.datetime(2021, 7, 5, 16, 1, 26), datetime.datetime(2021, 7, 5, 16, 20, 57), datetime.datetime(2021, 7, 5, 16, 21, 58), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 18, 53, 35), datetime.datetime(2021, 7, 5, 18, 53, 35), datetime.datetime(2021, 7, 5, 18, 53, 35), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 6, 23, 24, 4), datetime.datetime(2021, 7, 6, 9, 21, 18), datetime.datetime(2021, 7, 7, 5, 29, 15), datetime.datetime(2021, 7, 7, 20, 53, 39), datetime.datetime(2021, 7, 7, 20, 53, 39), datetime.datetime(2021, 7, 1, 19, 55, 5), datetime.datetime(2021, 7, 1, 19, 55, 5), datetime.datetime(2021, 7, 1, 19, 55, 5), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 51, 28), datetime.datetime(2021, 6, 24, 18, 48, 44), datetime.datetime(2021, 6, 24, 18, 48, 44), datetime.datetime(2021, 6, 25, 9, 36, 30), datetime.datetime(2021, 6, 25, 15, 59, 22), datetime.datetime(2021, 6, 25, 15, 59, 22), datetime.datetime(2021, 6, 25, 18, 51, 4), datetime.datetime(2021, 6, 25, 18, 51, 4), datetime.datetime(2021, 6, 25, 18, 51, 4), datetime.datetime(2021, 6, 25, 19, 6, 45), datetime.datetime(2021, 6, 25, 19, 6, 45), datetime.datetime(2021, 6, 26, 5, 50), datetime.datetime(2021, 6, 26, 6, 8, 12), datetime.datetime(2021, 6, 26, 7, 20, 4), datetime.datetime(2021, 6, 26, 8, 4, 5), datetime.datetime(2021, 6, 28, 4, 0, 10), datetime.datetime(2021, 6, 28, 4, 0, 10), datetime.datetime(2021, 6, 28, 5, 10, 49), datetime.datetime(2021, 6, 28, 5, 54, 2), datetime.datetime(2021, 6, 28, 5, 59, 22), datetime.datetime(2021, 6, 28, 6, 11, 31), datetime.datetime(2021, 6, 28, 6, 16, 13), datetime.datetime(2021, 6, 28, 6, 16, 13), datetime.datetime(2021, 6, 28, 6, 16, 13), datetime.datetime(2021, 6, 28, 6, 24, 17), datetime.datetime(2021, 6, 28, 7, 10, 27), datetime.datetime(2021, 6, 28, 7, 10, 27), datetime.datetime(2021, 6, 30, 18, 21, 24), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 29, 4, 4, 44), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 29, 4, 11, 46), datetime.datetime(2021, 6, 29, 4, 11, 46), datetime.datetime(2021, 6, 29, 4, 11, 46), datetime.datetime(2021, 6, 28, 19, 22, 13), datetime.datetime(2021, 6, 28, 19, 22, 13), datetime.datetime(2021, 6, 28, 19, 22, 13), datetime.datetime(2021, 6, 29, 23, 26, 9), datetime.datetime(2021, 6, 29, 23, 29, 56), datetime.datetime(2021, 6, 29, 9, 12, 54), datetime.datetime(2021, 6, 29, 10, 20, 53), datetime.datetime(2021, 6, 30, 11, 42, 13), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 7, 2, 3, 39, 27), datetime.datetime(2021, 7, 2, 8, 4, 57), datetime.datetime(2021, 7, 1, 3, 53, 56), datetime.datetime(2021, 7, 1, 5, 12, 45), datetime.datetime(2021, 7, 1, 5, 40, 7), datetime.datetime(2021, 7, 1, 21, 13, 59), datetime.datetime(2021, 7, 1, 21, 13, 59), datetime.datetime(2021, 7, 1, 21, 38, 23), datetime.datetime(2021, 7, 1, 21, 41, 34), datetime.datetime(2021, 7, 1, 10, 2, 21), datetime.datetime(2021, 7, 1, 10, 11, 28), datetime.datetime(2021, 7, 2, 12, 1, 48), datetime.datetime(2021, 7, 2, 12, 31, 59), datetime.datetime(2021, 7, 2, 4, 50, 39), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 2, 18, 52, 52), datetime.datetime(2021, 7, 3, 14, 5, 58), datetime.datetime(2021, 7, 3, 14, 14, 19), datetime.datetime(2021, 7, 3, 16, 45, 6), datetime.datetime(2021, 7, 3, 17, 21, 43), datetime.datetime(2021, 7, 3, 20, 58, 42), datetime.datetime(2021, 7, 4, 0, 26, 24), datetime.datetime(2021, 7, 4, 0, 26, 24), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 5, 16, 20, 57), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51)]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [28]:
df

,ID,IN_TIME,REF_ID,CON_NUM,CON_SIZE,STATUS,Out_Time
0,322,14-03-22 15:46:44,ALO11887,SPRE0057868,20,L,2021-06-24 17:02:53
1,322,14-03-22 15:46:44,ALO11887,ANKJ1447873,20,L,2021-06-24 17:02:53
2,322,14-03-22 15:46:44,ALO11887,ACLU3053768,20,L,2021-06-24 17:02:53
3,326,17-04-22 04:41:42,DP02MAR10,BUDE0578181,40,L,2021-08-26 01:41:04
4,326,17-04-22 04:41:42,DP02MAR10,UPDU1678037,20,E,2021-08-23 18:32:42
...,...,...,...,...,...,...,...
345,554,20-03-22 14:48:13,ALO11980-98997-330244,IVIP5581378,20,L,2021-07-05 16:25:51
346,555,20-03-22 14:48:13,ALO11980-98998-330245,XEFF1829672,20,L,2021-07-05 16:25:51
347,556,20-03-22 14:48:13,ALO11980-98999-330246,BFIU2996554,20,L,2021-07-05 16:25:51
348,557,20-03-22 14:48:13,ALO11980-99000-330247,RDCW7179253,20,L,2021-07-05 16:25:51
349,558,20-03-22 14:48:13,ALO11980-99001-330248,NUDE0749531,20,L,2021-07-05 16:25:51

In [31]:
df.to_csv('Predicted_Data')

In [30]:
df.to_excel('Predicted_Data')

ValueError: No engine for filetype: ''