In [2]:
import pandas as pd

In [2]:
df=pd.read_csv('Past In and Out.csv')

In [12]:
from datetime import datetime
def Milli(X):
    given_date_time = X
    epoch = datetime(1970, 1, 1)
    time_difference = given_date_time - epoch
    total_seconds = time_difference.total_seconds()
    milliseconds = int(total_seconds * 1000)
    return milliseconds

def Date_Time(X):
    seconds = X / 1000
    date_time = datetime.fromtimestamp(seconds)
    date_time1= date_time.strftime('%d-%m-%y %H:%M:%S')
    return date_time1

In [4]:
from datetime import datetime
import pandas as pd
IN_Time=[]
OUT_Time=[]

for i in range(df.shape[0]):
    x1 = datetime.strptime(df['IN_TIME'][i], '%d-%m-%y %H:%M:%S')
    x1m = Milli(x1)
    IN_Time.append(x1m)
    y1 = datetime.strptime(df['OUT_TIME'][i], '%d-%m-%y %H:%M:%S')
    y1m = Milli(y1)
    IN_Time.append(x1m)
    OUT_Time.append(y1m)
In = pd.DataFrame(IN_Time)
Out = pd.DataFrame(OUT_Time)

In [5]:
df.drop(columns='REF_ID',axis=1,inplace=True)
df.drop(columns='VALIDITY',axis=1,inplace=True)
df.drop(columns='CON_NUM',axis=1,inplace=True)
df.drop(columns='IN_TIME',axis=1,inplace=True)
df.drop(columns='OUT_TIME',axis=1,inplace=True)

In [6]:
df['In_time'] = In
df['Out_time'] = Out

In [7]:
df.dropna(axis=0,inplace=True)

In [8]:
df.reset_index(inplace=True)

In [9]:
df1=pd.get_dummies(data=df['STATUS'],drop_first=True)
df['L']=df1

In [10]:
df.drop(columns='STATUS',axis=1,inplace=True)
df.drop(columns='index',axis=1,inplace=True)

In [11]:
Time_diff = []
for i in range(df.shape[0]):
    Time_diff.append(df['Out_time'][i]-df['In_time'][i])
    
df['Time_Diff'] = Time_diff
def find_outliers(df,col):
    q1=df[col].quantile(0.25)
    q3=df[col].quantile(0.75)
    IQR=q3-q1
    lv=q1-1.5*IQR
    hv=q3+1.5*IQR
    df=df[(df[col]<=hv) | (df[col]>=lv)]
    return df
find_outliers(df,'Time_Diff')

       CON_SIZE        In_time       Out_time  L    Time_Diff
0          40.0  1668216594000  1675732992000  0   7516398000
1          40.0  1668216594000  1675366422000  0   7149828000
2          20.0  1669124439000  1676005749000  0   6881310000
3          20.0  1669124439000  1677572528000  0   8448089000
4          20.0  1670173982000  1681752196000  0  11578214000
...         ...            ...            ... ..          ...
24524      40.0  1678738917000  1682467275000  1   3728358000
24525      40.0  1678738917000  1682478340000  1   3739423000
24526      20.0  1678738917000  1682474490000  1   3735573000
24527      40.0  1678740230000  1682488202000  0   3747972000
24528      40.0  1678740230000  1682464069000  1   3723839000

[24529 rows x 5 columns]

In [12]:
df.drop(columns='Time_Diff',axis=1,inplace=True)

In [13]:
x=df.drop('Out_time',axis=1)
y=df['Out_time']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(19623, 3)
(4906, 3)
(19623,)
(4906,)

In [14]:
import numpy 
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

print(lr.coef_)
print(lr.intercept_)

[2.58619498e+06 1.84151937e+00 1.46778791e+08]
-1409148897269.0027

In [15]:
y_pred=lr.predict(x_test)
print(y_pred)
print(y_test)

[1.68175294e+12 1.68044246e+12 1.68091108e+12 ... 1.68220033e+12
 1.67711545e+12 1.67787852e+12]
20997    1681911443000
12655    1679226166000
19424    1681999096000
16029    1681056131000
9602     1678633379000
             ...
3244     1675876990000
3877     1676609170000
23117    1682557658000
7149     1677308338000
5655     1677050680000
Name: Out_time, Length: 4906, dtype: int64

In [16]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_pred,y_test)
mse

1.257241066359832e+18

In [17]:
df=pd.read_csv('Insert data.csv')
x = df['IN_TIME'][0]
x1 = datetime.strptime(x, '%d-%m-%y %H:%M:%S')
x1m=Milli(x1)
Out=[[40,x1m,1]]
x1=lr.predict(Out)
Outtime = datetime.strptime(Date_Time(int(x1)),'%d-%m-%y %H:%M:%S')
print(Outtime)

2021-06-25 07:24:57

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [18]:
x1 = datetime.strptime(Date_Time(int(x1)),'%d-%m-%y %H:%M:%S')

In [19]:
print(Outtime==Outtime)

True

In [20]:
df = pd.read_csv('Insert data.csv')

In [22]:
df

,ID,IN_TIME,REF_ID,CON_NUM,CON_SIZE,STATUS
0,322,14-03-22 15:46:44,ALO11887,SPRE0057868,20,L
1,322,14-03-22 15:46:44,ALO11887,ANKJ1447873,20,L
2,322,14-03-22 15:46:44,ALO11887,ACLU3053768,20,L
3,326,17-04-22 04:41:42,DP02MAR10,BUDE0578181,40,L
4,326,17-04-22 04:41:42,DP02MAR10,UPDU1678037,20,E
...,...,...,...,...,...,...
345,554,20-03-22 14:48:13,ALO11980-98997-330244,IVIP5581378,20,L
346,555,20-03-22 14:48:13,ALO11980-98998-330245,XEFF1829672,20,L
347,556,20-03-22 14:48:13,ALO11980-98999-330246,BFIU2996554,20,L
348,557,20-03-22 14:48:13,ALO11980-99000-330247,RDCW7179253,20,L
349,558,20-03-22 14:48:13,ALO11980-99001-330248,NUDE0749531,20,L

In [23]:
OutTime=[]
s=0
for i in range(df.shape[0]):
    if df['STATUS'][i] == 'L':
        s=1
    else:
        s=0
    pre = Predict_Out_Time(df['IN_TIME'],df['CON_SIZE'],s)
    OutTime.append(pre)

NameError: name 'Predict_Out_Time' is not defined

In [26]:
type(df['IN_TIME'][0])

str

In [27]:
import numpy
import pandas as pd
from datetime import datetime
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


def Predict_Out_Time(Time,size,state):
    df = pd.read_csv('Past In and Out.csv')

    def Milli(X):
        given_date_time = X
        epoch = datetime(1970, 1, 1)
        time_difference = given_date_time - epoch
        total_seconds = time_difference.total_seconds()
        milliseconds = int(total_seconds * 1000)
        return milliseconds

    def Date_Time(X):
        seconds = X / 1000
        date_time = datetime.fromtimestamp(seconds)
        date_time1= date_time.strftime('%d-%m-%y %H:%M:%S')
        return date_time1

    IN_Time = []
    OUT_Time = []
    for i in range(df.shape[0]):
        x1 = datetime.strptime(df['IN_TIME'][i], '%d-%m-%y %H:%M:%S')
        x1m = Milli(x1)
        IN_Time.append(x1m)
        y1 = datetime.strptime(df['OUT_TIME'][i], '%d-%m-%y %H:%M:%S')
        y1m = Milli(y1)
        IN_Time.append(x1m)
        OUT_Time.append(y1m)
    In = pd.DataFrame(IN_Time)
    Out = pd.DataFrame(OUT_Time)
    df.drop(columns='REF_ID', axis=1, inplace=True)
    df.drop(columns='VALIDITY', axis=1, inplace=True)
    df.drop(columns='CON_NUM', axis=1, inplace=True)
    df.drop(columns='IN_TIME', axis=1, inplace=True)
    df.drop(columns='OUT_TIME', axis=1, inplace=True)
    df['In_time'] = In
    df['Out_time'] = Out
    df.dropna(axis=0, inplace=True)
    df.reset_index(inplace=True)
    df1 = pd.get_dummies(data=df['STATUS'], drop_first=True)
    df['L'] = df1
    df.drop(['STATUS'], axis=1, inplace=True)
    df.drop(columns='index',axis=1,inplace=True)
    Time_diff = []
    for i in range(df.shape[0]):
        Time_diff.append(df['Out_time'][i]-df['In_time'][i])
        
    df['Time_Diff'] = Time_diff
    def find_outliers(df,col):
        q1=df[col].quantile(0.25)
        q3=df[col].quantile(0.75)
        IQR=q3-q1
        lv=q1-1.5*IQR
        hv=q3+1.5*IQR
        df=df[(df[col]<=hv) | (df[col]>=lv)]
        return df
    find_outliers(df,'Time_Diff')
    df.drop(columns='Time_Diff',axis=1,inplace=True)
    x = df.drop('Out_time', axis=1)
    y = df['Out_time']
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
    # print(x_train.shape)
    # print(x_test.shape)
    # print(y_train.shape)
    # print(y_test.shape)
    lr = LinearRegression()
    lr.fit(x_train, y_train)
    # print(lr.coef_)
    # print(lr.intercept_)
    y_pred = lr.predict(x_test)
    # print(y_pred)
    # print(y_test)
    mse = mean_squared_error(y_pred, y_test)
    # mse
    df = pd.read_csv('Insert data.csv')
    x = Time
    x1 = datetime.strptime(x, '%d-%m-%y %H:%M:%S')
    x1m = Milli(x1)
    Out = [[size, x1m, state]]
    x1=lr.predict(Out)
    Outtime = datetime.strptime(Date_Time(int(x1)),'%d-%m-%y %H:%M:%S')
    return Outtime


pre = Predict_Out_Time('14-03-22 15:46:44',20,1)
print(pre)

df = pd.read_csv('Insert data.csv')
OutTime=[]
s=0
for i in range(df.shape[0]):
    if df['STATUS'][i] == 'L':
        s=1
    else:
        s=0
    pre = Predict_Out_Time(df['IN_TIME'][i],df['CON_SIZE'][i],s)
    OutTime.append(pre)
print(OutTime)
df['Out_Time'] = OutTime

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

2021-06-24 17:02:53

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

[datetime.datetime(2021, 6, 24, 17, 2, 53), datetime.datetime(2021, 6, 24, 17, 2, 53), datetime.datetime(2021, 6, 24, 17, 2, 53), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 23, 18, 32, 42), datetime.datetime(2021, 8, 25, 11, 19), datetime.datetime(2021, 8, 25, 11, 19), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 26, 1, 41, 4), datetime.datetime(2021, 8, 24, 8, 54, 45), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 0, 51, 41), datetime.datetime(2021, 6, 27, 1, 2, 24), datetime.datetime(2021, 6, 27, 1, 43, 55), datetime.datetime(2021, 6, 27, 2, 22, 48), datetime.datetime(2021, 6, 24, 20, 25, 10), datetime.datetime(2021, 6, 24, 20, 49, 7), datetime.datetime(2021, 6, 27, 8, 45, 41), datetime.datetime(2021, 6, 27, 8, 45, 41), datetime.datetime(2021, 6, 27, 11, 53, 4), datetime.datetime(2021, 6, 27, 11, 53, 4), datetime.datetime(2021, 6, 27, 22, 36, 18), datetime.datetime(2021, 6, 27, 22, 54, 30), datetime.datetime(2021, 6, 28, 0, 6, 23), datetime.datetime(2021, 6, 29, 21, 36, 8), datetime.datetime(2021, 6, 29, 21, 36, 8), datetime.datetime(2021, 6, 29, 21, 57, 8), datetime.datetime(2021, 6, 29, 22, 40, 20), datetime.datetime(2021, 6, 29, 22, 45, 41), datetime.datetime(2021, 6, 29, 22, 57, 50), datetime.datetime(2021, 6, 29, 23, 10, 36), datetime.datetime(2021, 6, 29, 23, 56, 46), datetime.datetime(2021, 6, 29, 23, 56, 46), datetime.datetime(2021, 6, 30, 4, 53, 27), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 7, 1, 16, 12, 28), datetime.datetime(2021, 7, 1, 16, 16, 15), datetime.datetime(2021, 7, 1, 1, 59, 13), datetime.datetime(2021, 7, 1, 3, 7, 12), datetime.datetime(2021, 7, 2, 1, 45, 11), datetime.datetime(2021, 7, 2, 1, 45, 11), datetime.datetime(2021, 7, 2, 4, 16, 11), datetime.datetime(2021, 6, 30, 13, 5, 42), datetime.datetime(2021, 6, 26, 20, 8, 38), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 24, 13, 0, 16), datetime.datetime(2021, 6, 26, 20, 8, 38), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 9, 46, 22), datetime.datetime(2021, 7, 2, 3, 39, 29), datetime.datetime(2021, 7, 2, 3, 39, 29), datetime.datetime(2021, 7, 2, 3, 39, 29), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 8, 4, 58), datetime.datetime(2021, 7, 2, 20, 40, 15), datetime.datetime(2021, 7, 2, 21, 59, 4), datetime.datetime(2021, 7, 2, 22, 26, 26), datetime.datetime(2021, 7, 3, 14, 0, 17), datetime.datetime(2021, 7, 3, 14, 0, 17), datetime.datetime(2021, 7, 3, 14, 24, 41), datetime.datetime(2021, 7, 3, 14, 27, 53), datetime.datetime(2021, 7, 3, 2, 57, 47), datetime.datetime(2021, 7, 4, 2, 20, 11), datetime.datetime(2021, 7, 4, 4, 48, 7), datetime.datetime(2021, 7, 4, 5, 18, 17), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 36, 58), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 4, 8, 16, 8), datetime.datetime(2021, 7, 4, 11, 39, 11), datetime.datetime(2021, 7, 5, 4, 13, 56), datetime.datetime(2021, 7, 5, 4, 25, 41), datetime.datetime(2021, 7, 5, 5, 4, 11), datetime.datetime(2021, 7, 5, 5, 16), datetime.datetime(2021, 7, 5, 5, 16), datetime.datetime(2021, 7, 4, 15, 19, 17), datetime.datetime(2021, 7, 4, 15, 28, 55), datetime.datetime(2021, 7, 4, 16, 16, 59), datetime.datetime(2021, 7, 4, 16, 16, 59), datetime.datetime(2021, 7, 5, 6, 52, 16), datetime.datetime(2021, 7, 5, 7, 0, 37), datetime.datetime(2021, 7, 4, 18, 4), datetime.datetime(2021, 7, 4, 18, 17, 7), datetime.datetime(2021, 7, 4, 18, 23, 52), datetime.datetime(2021, 7, 4, 18, 50, 56), datetime.datetime(2021, 7, 5, 9, 31, 25), datetime.datetime(2021, 7, 5, 10, 8, 2), datetime.datetime(2021, 7, 4, 21, 16, 8), datetime.datetime(2021, 7, 5, 12, 45, 53), datetime.datetime(2021, 7, 5, 14, 16, 38), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 44, 28), datetime.datetime(2021, 7, 5, 15, 56, 20), datetime.datetime(2021, 7, 5, 16, 1, 26), datetime.datetime(2021, 7, 5, 16, 20, 57), datetime.datetime(2021, 7, 5, 16, 21, 58), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 18, 53, 35), datetime.datetime(2021, 7, 5, 18, 53, 35), datetime.datetime(2021, 7, 5, 18, 53, 35), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 5, 19, 11, 17), datetime.datetime(2021, 7, 6, 23, 24, 4), datetime.datetime(2021, 7, 6, 9, 21, 18), datetime.datetime(2021, 7, 7, 5, 29, 15), datetime.datetime(2021, 7, 7, 20, 53, 39), datetime.datetime(2021, 7, 7, 20, 53, 39), datetime.datetime(2021, 7, 1, 19, 55, 5), datetime.datetime(2021, 7, 1, 19, 55, 5), datetime.datetime(2021, 7, 1, 19, 55, 5), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 5, 22), datetime.datetime(2021, 6, 25, 8, 51, 28), datetime.datetime(2021, 6, 24, 18, 48, 44), datetime.datetime(2021, 6, 24, 18, 48, 44), datetime.datetime(2021, 6, 25, 9, 36, 30), datetime.datetime(2021, 6, 25, 15, 59, 22), datetime.datetime(2021, 6, 25, 15, 59, 22), datetime.datetime(2021, 6, 25, 18, 51, 4), datetime.datetime(2021, 6, 25, 18, 51, 4), datetime.datetime(2021, 6, 25, 18, 51, 4), datetime.datetime(2021, 6, 25, 19, 6, 45), datetime.datetime(2021, 6, 25, 19, 6, 45), datetime.datetime(2021, 6, 26, 5, 50), datetime.datetime(2021, 6, 26, 6, 8, 12), datetime.datetime(2021, 6, 26, 7, 20, 4), datetime.datetime(2021, 6, 26, 8, 4, 5), datetime.datetime(2021, 6, 28, 4, 0, 10), datetime.datetime(2021, 6, 28, 4, 0, 10), datetime.datetime(2021, 6, 28, 5, 10, 49), datetime.datetime(2021, 6, 28, 5, 54, 2), datetime.datetime(2021, 6, 28, 5, 59, 22), datetime.datetime(2021, 6, 28, 6, 11, 31), datetime.datetime(2021, 6, 28, 6, 16, 13), datetime.datetime(2021, 6, 28, 6, 16, 13), datetime.datetime(2021, 6, 28, 6, 16, 13), datetime.datetime(2021, 6, 28, 6, 24, 17), datetime.datetime(2021, 6, 28, 7, 10, 27), datetime.datetime(2021, 6, 28, 7, 10, 27), datetime.datetime(2021, 6, 30, 18, 21, 24), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 29, 4, 4, 44), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 30, 20, 51, 3), datetime.datetime(2021, 6, 29, 4, 11, 46), datetime.datetime(2021, 6, 29, 4, 11, 46), datetime.datetime(2021, 6, 29, 4, 11, 46), datetime.datetime(2021, 6, 28, 19, 22, 13), datetime.datetime(2021, 6, 28, 19, 22, 13), datetime.datetime(2021, 6, 28, 19, 22, 13), datetime.datetime(2021, 6, 29, 23, 26, 9), datetime.datetime(2021, 6, 29, 23, 29, 56), datetime.datetime(2021, 6, 29, 9, 12, 54), datetime.datetime(2021, 6, 29, 10, 20, 53), datetime.datetime(2021, 6, 30, 11, 42, 13), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 17, 0, 3), datetime.datetime(2021, 6, 30, 20, 33, 28), datetime.datetime(2021, 7, 2, 3, 39, 27), datetime.datetime(2021, 7, 2, 8, 4, 57), datetime.datetime(2021, 7, 1, 3, 53, 56), datetime.datetime(2021, 7, 1, 5, 12, 45), datetime.datetime(2021, 7, 1, 5, 40, 7), datetime.datetime(2021, 7, 1, 21, 13, 59), datetime.datetime(2021, 7, 1, 21, 13, 59), datetime.datetime(2021, 7, 1, 21, 38, 23), datetime.datetime(2021, 7, 1, 21, 41, 34), datetime.datetime(2021, 7, 1, 10, 2, 21), datetime.datetime(2021, 7, 1, 10, 11, 28), datetime.datetime(2021, 7, 2, 12, 1, 48), datetime.datetime(2021, 7, 2, 12, 31, 59), datetime.datetime(2021, 7, 2, 4, 50, 39), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 34, 27), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 3, 21, 53, 10), datetime.datetime(2021, 7, 2, 18, 52, 52), datetime.datetime(2021, 7, 3, 14, 5, 58), datetime.datetime(2021, 7, 3, 14, 14, 19), datetime.datetime(2021, 7, 3, 16, 45, 6), datetime.datetime(2021, 7, 3, 17, 21, 43), datetime.datetime(2021, 7, 3, 20, 58, 42), datetime.datetime(2021, 7, 4, 0, 26, 24), datetime.datetime(2021, 7, 4, 0, 26, 24), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 6, 2, 12, 28), datetime.datetime(2021, 7, 5, 16, 20, 57), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51), datetime.datetime(2021, 7, 5, 16, 25, 51)]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [28]:
df

,ID,IN_TIME,REF_ID,CON_NUM,CON_SIZE,STATUS,Out_Time
0,322,14-03-22 15:46:44,ALO11887,SPRE0057868,20,L,2021-06-24 17:02:53
1,322,14-03-22 15:46:44,ALO11887,ANKJ1447873,20,L,2021-06-24 17:02:53
2,322,14-03-22 15:46:44,ALO11887,ACLU3053768,20,L,2021-06-24 17:02:53
3,326,17-04-22 04:41:42,DP02MAR10,BUDE0578181,40,L,2021-08-26 01:41:04
4,326,17-04-22 04:41:42,DP02MAR10,UPDU1678037,20,E,2021-08-23 18:32:42
...,...,...,...,...,...,...,...
345,554,20-03-22 14:48:13,ALO11980-98997-330244,IVIP5581378,20,L,2021-07-05 16:25:51
346,555,20-03-22 14:48:13,ALO11980-98998-330245,XEFF1829672,20,L,2021-07-05 16:25:51
347,556,20-03-22 14:48:13,ALO11980-98999-330246,BFIU2996554,20,L,2021-07-05 16:25:51
348,557,20-03-22 14:48:13,ALO11980-99000-330247,RDCW7179253,20,L,2021-07-05 16:25:51
349,558,20-03-22 14:48:13,ALO11980-99001-330248,NUDE0749531,20,L,2021-07-05 16:25:51

In [31]:
# df.to_csv('Predicted_Data')

In [5]:
df = pd.read_csv('Predicted_Data.csv')

In [6]:
df

,Unnamed: 0,ID,IN_TIME,REF_ID,CON_NUM,CON_SIZE,STATUS,Out_Time
0,0,322,14-03-22 15:46:44,ALO11887,SPRE0057868,20,L,2021-06-24 17:02:53
1,1,322,14-03-22 15:46:44,ALO11887,ANKJ1447873,20,L,2021-06-24 17:02:53
2,2,322,14-03-22 15:46:44,ALO11887,ACLU3053768,20,L,2021-06-24 17:02:53
3,3,326,17-04-22 04:41:42,DP02MAR10,BUDE0578181,40,L,2021-08-26 01:41:04
4,4,326,17-04-22 04:41:42,DP02MAR10,UPDU1678037,20,E,2021-08-23 18:32:42
...,...,...,...,...,...,...,...,...
345,345,554,20-03-22 14:48:13,ALO11980-98997-330244,IVIP5581378,20,L,2021-07-05 16:25:51
346,346,555,20-03-22 14:48:13,ALO11980-98998-330245,XEFF1829672,20,L,2021-07-05 16:25:51
347,347,556,20-03-22 14:48:13,ALO11980-98999-330246,BFIU2996554,20,L,2021-07-05 16:25:51
348,348,557,20-03-22 14:48:13,ALO11980-99000-330247,RDCW7179253,20,L,2021-07-05 16:25:51
349,349,558,20-03-22 14:48:13,ALO11980-99001-330248,NUDE0749531,20,L,2021-07-05 16:25:51

In [9]:
print(df['IN_TIME'][0]>df['Out_Time'][0])

False

In [32]:
print(type(df['IN_TIME'][0]))
type(df['Out_Time'][0])

<class 'str'>

str

In [47]:
x1 = 
print(x1)

2015-03-14 15:46:44

In [22]:
type(x1)

datetime.datetime

In [23]:
print(x1)

2022-03-14 15:46:44

In [94]:
import numpy as np
area={}
from datetime import datetime

def Milli(X):
    given_date_time = X
    epoch = datetime(1970, 1, 1)
    time_difference = given_date_time - epoch
    total_seconds = time_difference.total_seconds()
    milliseconds = int(total_seconds * 1000)
    return milliseconds
def Date_Time(X):
    seconds = X / 1000
    date_time = datetime.fromtimestamp(seconds)
    date_time1= date_time.strftime('%d-%m-%Y %H:%M:%S')
    return date_time1
# /////////////////////////////grid created//////////////////////////////////////////////////

def create_grid(are,lev,col,row):
    global area
    if(are not in area):
        shape = (lev, col, row)
        #       val=how many days for exporting container       
        myList = [[[{'val':0,'id':'','below_container_export_days':0,'container_size':0} for r in range(row)] for c in range(col)]for l in range(lev)]   
        area[are] = {'shape':myList,'container_type':' ','size':row*col*lev,'full':False}
        print('grid created!')
    else:
        print('Area already present!')



# /////////////////////////////grid created//////////////////////////////////////////////////
# /////////////////////////////Finding and placing container/////////////////////////////////
def placement(id,container_type,container_return_days,container_size):
    global area
    newinsert=True
    for i in area:
        if(container_type==area[i]['container_type']):
            newinsert=False
    
    if(newinsert==True):
        maxavailableareasize=0
        maxavailablearea=''
        is_space_available_flag=False
        for i in area:
            if area[i]['container_type']==' ' and area[i]['size']>maxavailableareasize :
                maxavailableareasize=area[i]['size']
                maxavailablearea=i
                is_space_available_flag=True
        if(is_space_available_flag==False):
            print('no more space left')
            return 0
        area[maxavailablearea]['container_type']=container_type
        placement(id,container_type,container_return_days,container_size)
        return 0
    else:
        insert_into_yard(id,container_type,container_return_days,container_size)

#///////////////////////////////insertion logic///////////////////////////////////////////////// 

def insert_into_yard(id,container_type,container_return_days,container_size):
            global area
            port_area=''
            for i in area:
                if(area[i]['container_type']==container_type and area[i]['full']==False):
                    port_area=i
                    break
            shapee=np.shape(area[port_area]['shape'])
            final_placement=''
            zero_flag=False
            for lev in range(shapee[0]):
                for col in range(shapee[1]):
                    for row in range(shapee[2]):
                            # if(lev!=3):
                                # print(lev,col,row,'below:',area[port_area]['shape'][lev+1][col][row]['below_container_export_days'],area[port_area]['shape'][lev][col][row]['val'])
                            # code for placement of size 20 container
                            if (container_size==20):
                                if(lev!=shapee[0]-1 and (area[port_area]['shape'][lev][col][row]['container_size']==0 or area[port_area]['shape'][lev][col][row]['container_size']==20)):
#                                     if(lev!=3):
#                                         print('idharhe::',lev,col,row,area[port_area]['shape'][lev][col][row]['val'],'=',container_return_days,area[port_area]['shape'][lev+1][col][row]['below_container_export_days'],'=',area[port_area]['shape'][lev][col][row]['val'],zero_flag)
                                    if(area[port_area]['shape'][lev][col][row]['val']>=container_return_days and area[port_area]['shape'][lev+1][col][row]['below_container_export_days']>=area[port_area]['shape'][lev][col][row]['val']):
                                        i=0
                                        flag=True
                                        for level in range(shapee[0]):
                                            # print(area[port_area]['shape'][level][col][row]['val'])
                                            if(area[port_area]['shape'][level][col][row]['val']==0):
                                                i=level
                                                flag=False
                                                break
                                        if(flag==False):
                                            final_placement=(i,col,row)
                                            zero_flag=True
                                    elif(area[port_area]['shape'][lev][col][row]['val']==0 and zero_flag==False):
                                        # print('idharr:',lev,col,row,area[port_area]['shape'][lev][col][row]['val'],zero_flag)
                                        final_placement=(lev,col,row)
                                        zero_flag=True
                                    elif(area[port_area]['shape'][lev][col][row]['val']<container_return_days):
                                        pass
                            # code for placement of size 40 container
                            else:
                                if(lev!=shapee[0]-1 and ((area[port_area]['shape'][lev][col][row]['container_size']==0 and row!=shapee[2]-1) or (area[port_area]['shape'][lev][col][row]['container_size']==40 and row!=shapee[2]-1))):  
                                    if(area[port_area]['shape'][lev][col][row]['val']>=container_return_days and area[port_area]['shape'][lev][col][row+1]['val']>=container_return_days and area[port_area]['shape'][lev+1][col][row]['below_container_export_days']>=area[port_area]['shape'][lev][col][row]['val'] and area[port_area]['shape'][lev+1][col][row+1]['below_container_export_days']>=area[port_area]['shape'][lev][col][row+1]['val']):
                                        i=0
                                        flag=True
                                        for level in range(shapee[0]):
                                            # print(area[port_area]['shape'][level][col][row]['val'])
                                            if(area[port_area]['shape'][level][col][row]['val']==0 and area[port_area]['shape'][level][col][row+1]['val']==0):
                                                i=level
                                                flag=False
                                                break
                                        if(flag==False):
                                            final_placement=(i,col,row)
                                            zero_flag=True
                                    elif(area[port_area]['shape'][lev][col][row]['val']==0 and area[port_area]['shape'][lev][col][row+1]['val']==0 and zero_flag==False):
                                            # print('idharr:',lev,col,row,area[port_area]['shape'][lev][col][row]['val'],zero_flag)
                                            final_placement=(lev,col,row)
                                            zero_flag=True
                                    elif(area[port_area]['shape'][lev][col][row]['val']<container_return_days):
                                        pass
            if(final_placement==''):
                area[port_area]['full']=True
                placement(id,container_type,container_return_days,container_size)
                return 0
            else:
                if (container_size==20 and final_placement[0]+1!=shapee[0]):
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['val']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['id']=id
                    area[port_area]['shape'][final_placement[0]+1][final_placement[1]][final_placement[2]]['below_container_export_days']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['container_size']=container_size
                elif (container_size==20 and final_placement[0]==shapee[0]-1):
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['val']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['id']=id
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['below_container_export_days']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['container_size']=container_size
                elif(container_size==40 and final_placement[0]+1!=shapee[0]):
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['val']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]+1]['val']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['id']=id
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]+1]['id']=id
                    area[port_area]['shape'][final_placement[0]+1][final_placement[1]][final_placement[2]]['below_container_export_days']=container_return_days
                    area[port_area]['shape'][final_placement[0]+1][final_placement[1]][final_placement[2]+1]['below_container_export_days']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['container_size']=container_size
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]+1]['container_size']=container_size
                else:
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['val']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]+1]['val']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['id']=id
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]+1]['id']=id
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['below_container_export_days']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]+1]['below_container_export_days']=container_return_days
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]]['container_size']=container_size
                    area[port_area]['shape'][final_placement[0]][final_placement[1]][final_placement[2]+1]['container_size']=container_size
                if(container_size==20 and len(str(final_placement[2]))==1):
                    list.append(str(port_area)+'0'+str(final_placement[2])+str(final_placement[1])+str(final_placement[0]))
                elif(container_size==20 and len(str(final_placement[2]))!=1):
                    list.append(str(port_area)+str(final_placement[2])+str(final_placement[1])+str(final_placement[0]))
                elif(container_size==40 and (len(str(final_placement[2]))==1 or final_placement[2]<9)):
                    list.append(str(port_area)+'0'+str(final_placement[2]+1)+str(final_placement[1])+str(final_placement[0]))
                else:
                    list.append(str(port_area)+str(final_placement[2]+1)+str(final_placement[1])+str(final_placement[0]))
                    
#///////////////////////////////insertion logic ends////////////////////////////////////////// 
# /////////////////////////////Finding and placing container ends////////////////////////////
# /////////////////////////////Displaying our array or containers////////////////////////////
def display():
    for i in area:
        print(i)
        print('container_type:',area[i]['container_type'],'size:',area[i]['size'],'full:',area[i]['full'])
        print()
        shapee=np.shape(area[i]['shape'])
        for lev in range(shapee[0]):
            print('Level',lev+1)
            for col in range(shapee[1]):
                for row in range(shapee[2]):
                    print('days:',area[i]['shape'][lev][col][row]['val'],' id:',area[i]['shape'][lev][col][row]['id'],' container size:',area[i]['shape'][lev][col][row]['container_size'],end=', ')
                print()
            print()
# /////////////////////////////Displaying our array or containers ends////////////////////////////
# ////////////////////////////////////////////creating grid/////////////////////////////////////////////

import pandas as pd
data = pd.read_csv("Yard locations.csv")
dict={}
loc = data['Location']
for i in loc:
    areaaa = i[0:1]
    row = int(i[1:3])
    col = ord(str(i[3:4]))-64
    lev = int(i[4:5])

    if (areaaa not in dict.keys()):
        dict[areaaa] = {'maxrow': row,'maxcol': col,'maxlev':lev}
    else:
        if (dict[areaaa]['maxrow'] < row):
            dict[areaaa]['maxrow'] = row
        if (dict[areaaa]['maxcol'] < col):
            dict[areaaa]['maxcol'] = col
        if (dict[areaaa]['maxlev'] < lev):
            dict[areaaa]['maxlev'] = lev

# create_grid('A',4,4,6)
# create_grid('B',4,4,6)
# display()
for i in dict:
#              name,  level  ,    col    ,    row
    create_grid(i,dict[i]['maxlev'],dict[i]['maxcol'],dict[i]['maxrow'])

df = pd.read_csv('Predicted_Data.csv')
list=[]
for i in range(df.shape[0]):
    x1 = datetime.strptime(df['Out_Time'][i], '%Y-%m-%d %H:%M:%S')
    D=Milli(x1)
    placement(str(df['CON_NUM'][i]),str(df['STATUS'][i]),int(D),int(df['CON_SIZE'][i]))
    print(i,'Number of set inserted!!')
display()

# x1 = datetime.strptime(df['Out_Time'][0],'%Y-%m-%d %H:%M:%S')
# D=Milli(x1)
# placement(str(df['CON_NUM'][0]),str(df['STATUS'][0]),int(D),int(df['CON_SIZE'][0]))
# x1 = datetime.strptime(df['Out_Time'][3],'%Y-%m-%d %H:%M:%S')
# D=Milli(x1)
# placement(str(df['CON_NUM'][3]),str(df['STATUS'][3]),int(D),int(df['CON_SIZE'][3]))
print(list)

# placement('001','Empty',5,20)
# display()
# ///////////////////////////////////some examples for entry of containers ends//////////////////////////////

# basic description:
#  by running the code you will see placement of some containers.
#  if size is 40 than 2 index is filled for one container while for 20 only 1 index is filled
#  display will be as follows: Name of area-->info of area-->level(height index)-->row and col(row and col index)|
#                                                          /\                                                    |
#                                                          |                                                     \/
#                                                          |<-----------------------------------------------------

grid created!
grid created!
grid created!
grid created!
grid created!
grid created!
grid created!
grid created!
grid created!
grid created!
grid created!
grid created!
0 Number of set inserted!!
1 Number of set inserted!!
2 Number of set inserted!!
3 Number of set inserted!!
4 Number of set inserted!!
5 Number of set inserted!!
6 Number of set inserted!!
7 Number of set inserted!!
8 Number of set inserted!!
9 Number of set inserted!!
10 Number of set inserted!!
11 Number of set inserted!!
12 Number of set inserted!!
13 Number of set inserted!!
14 Number of set inserted!!
15 Number of set inserted!!
16 Number of set inserted!!
17 Number of set inserted!!
18 Number of set inserted!!
19 Number of set inserted!!
20 Number of set inserted!!
21 Number of set inserted!!
22 Number of set inserted!!
23 Number of set inserted!!
24 Number of set inserted!!
25 Number of set inserted!!
26 Number of set inserted!!
27 Number of set inserted!!
28 Number of set inserted!!
29 Number of set inserted!!
30 Number of set inserted!!
31 Number of set inserted!!
32 Number of set inserted!!
33 Number of set inserted!!
34 Number of set inserted!!
35 Number of set inserted!!
36 Number of set inserted!!
37 Number of set inserted!!
38 Number of set inserted!!
39 Number of set inserted!!
40 Number of set inserted!!
41 Number of set inserted!!
42 Number of set inserted!!
43 Number of set inserted!!
44 Number of set inserted!!
45 Number of set inserted!!
46 Number of set inserted!!
47 Number of set inserted!!
48 Number of set inserted!!
49 Number of set inserted!!
50 Number of set inserted!!
51 Number of set inserted!!
52 Number of set inserted!!
53 Number of set inserted!!
54 Number of set inserted!!
55 Number of set inserted!!
56 Number of set inserted!!
57 Number of set inserted!!
58 Number of set inserted!!
59 Number of set inserted!!
60 Number of set inserted!!
61 Number of set inserted!!
62 Number of set inserted!!
63 Number of set inserted!!
64 Number of set inserted!!
65 Number of set inserted!!
66 Number of set inserted!!
67 Number of set inserted!!
68 Number of set inserted!!
69 Number of set inserted!!
70 Number of set inserted!!
71 Number of set inserted!!
72 Number of set inserted!!
73 Number of set inserted!!
74 Number of set inserted!!
75 Number of set inserted!!
76 Number of set inserted!!
77 Number of set inserted!!
78 Number of set inserted!!
79 Number of set inserted!!
80 Number of set inserted!!
81 Number of set inserted!!
82 Number of set inserted!!
83 Number of set inserted!!
84 Number of set inserted!!
85 Number of set inserted!!
86 Number of set inserted!!
87 Number of set inserted!!
88 Number of set inserted!!
89 Number of set inserted!!
90 Number of set inserted!!
91 Number of set inserted!!
92 Number of set inserted!!
93 Number of set inserted!!
94 Number of set inserted!!
95 Number of set inserted!!
96 Number of set inserted!!
97 Number of set inserted!!
98 Number of set inserted!!
99 Number of set inserted!!
100 Number of set inserted!!
101 Number of set inserted!!
102 Number of set inserted!!
103 Number of set inserted!!
104 Number of set inserted!!
105 Number of set inserted!!
106 Number of set inserted!!
107 Number of set inserted!!
108 Number of set inserted!!
109 Number of set inserted!!
110 Number of set inserted!!
111 Number of set inserted!!
112 Number of set inserted!!
113 Number of set inserted!!
114 Number of set inserted!!
115 Number of set inserted!!
116 Number of set inserted!!
117 Number of set inserted!!
118 Number of set inserted!!
119 Number of set inserted!!
120 Number of set inserted!!
121 Number of set inserted!!
122 Number of set inserted!!
123 Number of set inserted!!
124 Number of set inserted!!
125 Number of set inserted!!
126 Number of set inserted!!
127 Number of set inserted!!
128 Number of set inserted!!
129 Number of set inserted!!
130 Number of set inserted!!
131 Number of set inserted!!
132 Number of set inserted!!
133 Number of set inserted!!
134 Number of set inserted!!
135 Number of set inserted!!
136 Number of set inserted!!
137 Number of set inserted!!
138 Number of set inserted!!
139 Number of set inserted!!
140 Number of set inserted!!
141 Number of set inserted!!
142 Number of set inserted!!
143 Number of set inserted!!
144 Number of set inserted!!
145 Number of set inserted!!
146 Number of set inserted!!
147 Number of set inserted!!
148 Number of set inserted!!
149 Number of set inserted!!
150 Number of set inserted!!
151 Number of set inserted!!
152 Number of set inserted!!
153 Number of set inserted!!
154 Number of set inserted!!
155 Number of set inserted!!
156 Number of set inserted!!
157 Number of set inserted!!
158 Number of set inserted!!
159 Number of set inserted!!
160 Number of set inserted!!
161 Number of set inserted!!
162 Number of set inserted!!
163 Number of set inserted!!
164 Number of set inserted!!
165 Number of set inserted!!
166 Number of set inserted!!
167 Number of set inserted!!
168 Number of set inserted!!
169 Number of set inserted!!
170 Number of set inserted!!
171 Number of set inserted!!
172 Number of set inserted!!
173 Number of set inserted!!
174 Number of set inserted!!
175 Number of set inserted!!
176 Number of set inserted!!
177 Number of set inserted!!
178 Number of set inserted!!
179 Number of set inserted!!
180 Number of set inserted!!
181 Number of set inserted!!
182 Number of set inserted!!
183 Number of set inserted!!
184 Number of set inserted!!
185 Number of set inserted!!
186 Number of set inserted!!
187 Number of set inserted!!
188 Number of set inserted!!
189 Number of set inserted!!
190 Number of set inserted!!
191 Number of set inserted!!
192 Number of set inserted!!
193 Number of set inserted!!
194 Number of set inserted!!
195 Number of set inserted!!
196 Number of set inserted!!
197 Number of set inserted!!
198 Number of set inserted!!
199 Number of set inserted!!
200 Number of set inserted!!
201 Number of set inserted!!
202 Number of set inserted!!
203 Number of set inserted!!
204 Number of set inserted!!
205 Number of set inserted!!
206 Number of set inserted!!
207 Number of set inserted!!
208 Number of set inserted!!
209 Number of set inserted!!
210 Number of set inserted!!
211 Number of set inserted!!
212 Number of set inserted!!
213 Number of set inserted!!
214 Number of set inserted!!
215 Number of set inserted!!
216 Number of set inserted!!
217 Number of set inserted!!
218 Number of set inserted!!
219 Number of set inserted!!
220 Number of set inserted!!
221 Number of set inserted!!
222 Number of set inserted!!
223 Number of set inserted!!
224 Number of set inserted!!
225 Number of set inserted!!
226 Number of set inserted!!
227 Number of set inserted!!
228 Number of set inserted!!
229 Number of set inserted!!
230 Number of set inserted!!
231 Number of set inserted!!
232 Number of set inserted!!
233 Number of set inserted!!
234 Number of set inserted!!
235 Number of set inserted!!
236 Number of set inserted!!
237 Number of set inserted!!
238 Number of set inserted!!
239 Number of set inserted!!
240 Number of set inserted!!
241 Number of set inserted!!
242 Number of set inserted!!
243 Number of set inserted!!
244 Number of set inserted!!
245 Number of set inserted!!
246 Number of set inserted!!
247 Number of set inserted!!
248 Number of set inserted!!
249 Number of set inserted!!
250 Number of set inserted!!
251 Number of set inserted!!
252 Number of set inserted!!
253 Number of set inserted!!
254 Number of set inserted!!
255 Number of set inserted!!
256 Number of set inserted!!
257 Number of set inserted!!
258 Number of set inserted!!
259 Number of set inserted!!
260 Number of set inserted!!
261 Number of set inserted!!
262 Number of set inserted!!
263 Number of set inserted!!
264 Number of set inserted!!
265 Number of set inserted!!
266 Number of set inserted!!
267 Number of set inserted!!
268 Number of set inserted!!
269 Number of set inserted!!
270 Number of set inserted!!
271 Number of set inserted!!
272 Number of set inserted!!
273 Number of set inserted!!
274 Number of set inserted!!
275 Number of set inserted!!
276 Number of set inserted!!
277 Number of set inserted!!
278 Number of set inserted!!
279 Number of set inserted!!
280 Number of set inserted!!
281 Number of set inserted!!
282 Number of set inserted!!
283 Number of set inserted!!
284 Number of set inserted!!
285 Number of set inserted!!
286 Number of set inserted!!
287 Number of set inserted!!
288 Number of set inserted!!
289 Number of set inserted!!
290 Number of set inserted!!
291 Number of set inserted!!
292 Number of set inserted!!
293 Number of set inserted!!
294 Number of set inserted!!
295 Number of set inserted!!
296 Number of set inserted!!
297 Number of set inserted!!
298 Number of set inserted!!
299 Number of set inserted!!
300 Number of set inserted!!
301 Number of set inserted!!
302 Number of set inserted!!
303 Number of set inserted!!
304 Number of set inserted!!
305 Number of set inserted!!
306 Number of set inserted!!
307 Number of set inserted!!
308 Number of set inserted!!
309 Number of set inserted!!
310 Number of set inserted!!
311 Number of set inserted!!
312 Number of set inserted!!
313 Number of set inserted!!
314 Number of set inserted!!
315 Number of set inserted!!
316 Number of set inserted!!
317 Number of set inserted!!
318 Number of set inserted!!
319 Number of set inserted!!
320 Number of set inserted!!
321 Number of set inserted!!
322 Number of set inserted!!
323 Number of set inserted!!
324 Number of set inserted!!
325 Number of set inserted!!
326 Number of set inserted!!
327 Number of set inserted!!
328 Number of set inserted!!
329 Number of set inserted!!
330 Number of set inserted!!
331 Number of set inserted!!
332 Number of set inserted!!
333 Number of set inserted!!
334 Number of set inserted!!
335 Number of set inserted!!
336 Number of set inserted!!
337 Number of set inserted!!
338 Number of set inserted!!
339 Number of set inserted!!
340 Number of set inserted!!
341 Number of set inserted!!
342 Number of set inserted!!
343 Number of set inserted!!
344 Number of set inserted!!
345 Number of set inserted!!
346 Number of set inserted!!
347 Number of set inserted!!
348 Number of set inserted!!
349 Number of set inserted!!
A
container_type: E size: 648 full: False

Level 1
days: 1629743562000  id: UPDU1678037  container size: 20, days: 1629743562000  id: ECHT3406160  container size: 20, days: 1629743562000  id: KASH0692064  container size: 20, days: 1629743562000  id: EINJ6527750  container size: 20, days: 1629743562000  id: ZHXH0287646  container size: 20, days: 1629795285000  id: WYJK6436245  container size: 40, days: 1629795285000  id: WYJK6436245  container size: 40, days: 1629795285000  id: IXDV3010411  container size: 40, days: 1629795285000  id: IXDV3010411  container size: 40, days: 1624539616000  id: DGKT5256545  container size: 20, days: 1624539616000  id: YLHV0651304  container size: 20, days: 1624539616000  id: JKTA6878904  container size: 20, days: 1624539616000  id: YOLQ8251652  container size: 20, days: 1624539616000  id: UMXS2905123  container size: 20, days: 1624539616000  id: QDKT8813569  container size: 20, days: 1624539616000  id: JTKL7850892  container size: 20, days: 1624539616000  id: FNRH7502812  container size: 20, days: 1624539616000  id: XERG9251948  container size: 20, days: 1624539616000  id: FCOI3850741  container size: 20, days: 1624539616000  id: OFNC3177311  container size: 20, days: 1624539616000  id: WKBW4986630  container size: 20, days: 1624539616000  id: AVCD1898388  container size: 20, days: 1624539616000  id: YQBR9421410  container size: 20, days: 1624539616000  id: XVWG8568291  container size: 20, days: 1624539616000  id: JSOV5440485  container size: 20, days: 1624539616000  id: TJMZ5079427  container size: 20, days: 1624539616000  id: PAAA2120707  container size: 20,
days: 1624539616000  id: IFXV6094144  container size: 20, days: 1624608322000  id: LMVV5233144  container size: 40, days: 1624608322000  id: LMVV5233144  container size: 40, days: 1624611088000  id: EVCX6471612  container size: 40, days: 1624611088000  id: EVCX6471612  container size: 40, days: 1624560524000  id: NRZP7107837  container size: 20, days: 1624613790000  id: AFIV9137108  container size: 40, days: 1624613790000  id: AFIV9137108  container size: 40, days: 1624636762000  id: IGAN8010156  container size: 40, days: 1624636762000  id: IGAN8010156  container size: 40, days: 1624647064000  id: OSMD5007086  container size: 40, days: 1624647064000  id: OSMD5007086  container size: 40, days: 1624648005000  id: TCWL4798985  container size: 40, days: 1624648005000  id: TCWL4798985  container size: 40, days: 1624686600000  id: KTPO9171145  container size: 40, days: 1624686600000  id: KTPO9171145  container size: 40, days: 1624687692000  id: NZOM2732820  container size: 40, days: 1624687692000  id: NZOM2732820  container size: 40, days: 1624692004000  id: RQNI6905644  container size: 40, days: 1624692004000  id: RQNI6905644  container size: 40, days: 1624694645000  id: ITOZ6675017  container size: 40, days: 1624694645000  id: ITOZ6675017  container size: 40, days: 1624852810000  id: RMUC0383428  container size: 40, days: 1624852810000  id: RMUC0383428  container size: 40, days: 1624857049000  id: TBEX8101246  container size: 40, days: 1624857049000  id: TBEX8101246  container size: 40, days: 1624908133000  id: ALFP7017888  container size: 20,
days: 1624859642000  id: LCFR6047548  container size: 40, days: 1624859642000  id: LCFR6047548  container size: 40, days: 1624859962000  id: SOUH0850602  container size: 40, days: 1624859962000  id: SOUH0850602  container size: 40, days: 1624860691000  id: VIMK4070111  container size: 40, days: 1624860691000  id: VIMK4070111  container size: 40, days: 1624860973000  id: YTXH3591892  container size: 40, days: 1624860973000  id: YTXH3591892  container size: 40, days: 1624861457000  id: VLRK3920146  container size: 40, days: 1624861457000  id: VLRK3920146  container size: 40, days: 1624864227000  id: FPEU7913266  container size: 40, days: 1624864227000  id: FPEU7913266  container size: 40, days: 1624939484000  id: MABD1665247  container size: 40, days: 1624939484000  id: MABD1665247  container size: 40, days: 1625009169000  id: RULN1854407  container size: 40, days: 1625009169000  id: RULN1854407  container size: 40, days: 1625009396000  id: UVXZ9343325  container size: 40, days: 1625009396000  id: UVXZ9343325  container size: 40, days: 1624957974000  id: PLMR7472611  container size: 20, days: 1624962053000  id: RFXY9930361  container size: 20, days: 1625053333000  id: CBJG4884201  container size: 40, days: 1625053333000  id: CBJG4884201  container size: 40, days: 1625072403000  id: ZRMD7959985  container size: 40, days: 1625072403000  id: ZRMD7959985  container size: 40, days: 1625111636000  id: EUXV6076453  container size: 20, days: 1625116365000  id: ECNA2299709  container size: 20, days: 1625118007000  id: OYZL9805337  container size: 20,
days: 1625174039000  id: JCLN3494031  container size: 40, days: 1625174039000  id: JCLN3494031  container size: 40, days: 1625175503000  id: CBVR9901354  container size: 40, days: 1625175503000  id: CBVR9901354  container size: 40, days: 1625175694000  id: DFHV8230663  container size: 40, days: 1625175694000  id: DFHV8230663  container size: 40, days: 1625133741000  id: AYOV6442794  container size: 20, days: 1625134288000  id: YFMT1627135  container size: 20, days: 1625227308000  id: JRBL0664316  container size: 40, days: 1625227308000  id: JRBL0664316  container size: 40, days: 1625229119000  id: BPLS9312444  container size: 40, days: 1625229119000  id: BPLS9312444  container size: 40, days: 1625201439000  id: MJBX6140275  container size: 20, days: 1625251972000  id: HSRD4189879  container size: 20, days: 1625321158000  id: NVTD0319326  container size: 40, days: 1625321158000  id: NVTD0319326  container size: 40, days: 1625321659000  id: AVVK3464374  container size: 40, days: 1625321659000  id: AVVK3464374  container size: 40, days: 1625330706000  id: ZWPG7151073  container size: 40, days: 1625330706000  id: ZWPG7151073  container size: 40, days: 1625332903000  id: VNIZ4316158  container size: 40, days: 1625332903000  id: VNIZ4316158  container size: 40, days: 1625345922000  id: VTJY5042023  container size: 40, days: 1625345922000  id: VTJY5042023  container size: 40, days: 1625358384000  id: GOVP2559517  container size: 40, days: 1625358384000  id: GOVP2559517  container size: 40, days: 0  id:   container size: 0,
days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0,
days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0, days: 0  id:   container size: 0,

Level 2
days: 1629743562000  id: FZPU2318420  container size: 20, days: 1629743562000  id: MPQD4457059  container size: 20, days: 1629743562000  id: CGHU4430259  container size: 20, days: 1629743562000  id: INOE3879979  container size: 20, days: 1629743562000  id: EPGG1844361  container size: 20, days: 1629795285000  id: ENVM9006489  container size: 40, days: 1629795285000  id: ENVM9006489  container size: 40, days: 1629795285000  id: YVCH7477380  container size: 40, days: 1629795285000  id: YVCH7477380  container size: 40, days: 1624539616000  id: QXPC8081666  container size: 20, days: 1624539616000  id: NUSR2822571  container size: 20, days: 1624539616000  id: LUOT7569694  container size: 20, days: 1624539616000  id: OVCP5695696  container size: 20, days: 1624539616000  id: JODX8439967  container size: 20, days: 1624539616000  id: DPSU9157776  container size: 20, days: 1624539616000  id: TCCC4925716  container size: 20, days: 1624539616000  id: BVVT7274866  container size: 20, days: 1624539616000  id: XWYU6427674  container size: 20, days: 1624539616000  id: JGLB2304098  container size: 20, days: 1624539616000  id: EIRZ8888854  container size: 20, days: 1624539616000  id: YEOL6580018  container size: 20, days: 1624539616000  id: GANP2813890  container size: 20, days: 1624539616000  id: LYSX6170054  container size: 20, days: 1624539616000  id: NGZH1213603  container size: 20, days: 1624539616000  id: IQPG3351348  container size: 20, days: 1624539616000  id: XUAJ0393148  container size: 20, days: 1624539616000  id: GLJZ2700800  container size: 20,

In [54]:
x1 = datetime.strptime(df['Out_Time'][0],'%Y-%m-%d %H:%M:%S')

In [55]:
print(x1)

2021-06-24 17:02:53

In [61]:
def Milli(X):
    given_date_time = X
    epoch = datetime(1970, 1, 1)
    time_difference = given_date_time - epoch
    total_seconds = time_difference.total_seconds()
    milliseconds = int(total_seconds * 1000)
    return milliseconds
def Date_Time(X):
    seconds = X / 1000
    date_time = datetime.fromtimestamp(seconds)
    date_time1= date_time.strftime('%d-%m-%Y %H:%M:%S')
    return date_time1

In [62]:
x=Milli(x1)
x

1624554173000

In [63]:
Date_Time(x)

'24-06-2021 22:32:53'

In [70]:
a=10
list=[]

In [78]:
list.append(a)
list

[10, 10, 10, 10, 10, 10, 10, 10]

In [95]:
print(list)

['J0000', 'J0001', 'J0002', 'J0200', 'A0000', 'A0001', 'A0002', 'A0003', 'A0100', 'A0101', 'A0102', 'A0103', 'A0200', 'A0201', 'A0202', 'A0203', 'A0300', 'A0301', 'A0302', 'A0303', 'A0400', 'A0401', 'J0300', 'J0301', 'A0600', 'A0601', 'A0602', 'J0201', 'J0202', 'J0500', 'J0501', 'J0502', 'J0700', 'A0603', 'J0701', 'J0702', 'J0900', 'J0901', 'J0902', 'A0800', 'J1100', 'J1101', 'J1102', 'J1300', 'J1301', 'J1302', 'J1500', 'A0801', 'J1501', 'J1502', 'J1700', 'J1701', 'J1900', 'J2100', 'J2300', 'A0402', 'A0403', 'J2500', 'J2501', 'J2700', 'J2701', 'J2900', 'J3100', 'J3300', 'J3500', 'J3501', 'J3700', 'J3900', 'J4100', 'J4300', 'J4500', 'J4700', 'J4701', 'J0302', 'J4900', 'J4901', 'J4902', 'J5100', 'J5300', 'J5400', 'J5500', 'J5700', 'J5701', 'J0110', 'A0802', 'J5702', 'A0900', 'A0901', 'A0902', 'A0903', 'A1000', 'A1001', 'A1002', 'A1003', 'A1100', 'A1101', 'A1102', 'A1103', 'A1200', 'A1201', 'A1202', 'A1203', 'A1300', 'A1301', 'A1302', 'A1303', 'A1400', 'A1401', 'A1402', 'A1403', 'A1500', 'A1501', 'A1502', 'A1503', 'A1600', 'A1601', 'A1602', 'A1603', 'A1700', 'A1701', 'A1702', 'A1703', 'A1800', 'A1801', 'A1802', 'A1803', 'A1900', 'A1901', 'A1902', 'A1903', 'A2000', 'A2001', 'A2002', 'A2003', 'A2100', 'A2101', 'A2102', 'A2103', 'A2200', 'A2201', 'A2202', 'A2203', 'A2300', 'A2301', 'A2302', 'A2303', 'A2400', 'A2401', 'A2402', 'A2403', 'A2500', 'A2501', 'A2502', 'A2503', 'A2600', 'A2601', 'A2602', 'A2603', 'A0010', 'A0011', 'A0012', 'A0013', 'J4702', 'J0310', 'J0311', 'J0312', 'J0510', 'J5800', 'J5801', 'J5802', 'J0610', 'J0611', 'J0612', 'J0710', 'J0711', 'J0712', 'J0810', 'J0910', 'J1010', 'J1210', 'J1211', 'J1410', 'J1610', 'J1710', 'J1910', 'J2110', 'J2310', 'J2410', 'J2411', 'J2510', 'J2610', 'J2611', 'J2612', 'J2710', 'J2711', 'J2810', 'J2910', 'J3110', 'J3310', 'J3510', 'J3710', 'J3711', 'J3810', 'J3910', 'J4010', 'J4011', 'J4210', 'J4410', 'J4510', 'J4610', 'J4710', 'J4810', 'J5010', 'J5210', 'J5310', 'J5510', 'J5710', 'J0120', 'J0121', 'J0122', 'J0320', 'J0520', 'J5810', 'J0620', 'J0720', 'J0820', 'J0920', 'J0921', 'J0922', 'J1020', 'J1021', 'J1022', 'J1120', 'J1220', 'J1221', 'J1222', 'J1320', 'J1321', 'J1322', 'J1420', 'J1421', 'J1422', 'J1620', 'J1720', 'J1820', 'J2020', 'J2021', 'J4012', 'J2712', 'J2412', 'A0803', 'A0210', 'A0211', 'A0212', 'A0410', 'A0510', 'A0511', 'A0710', 'A0910', 'A0911', 'A1110', 'A1111', 'A1112', 'A1310', 'A1311', 'A1510', 'A1710', 'A1910', 'A2110', 'A2310', 'A2311', 'A2510', 'A0120', 'A0320', 'A0520', 'A0720', 'A0721', 'A0722', 'A0920', 'A1120', 'A1121', 'J2022', 'J3712', 'J1212', 'A1320', 'J1721', 'J1722', 'J0621', 'J0622', 'J0421', 'J0422', 'J5811', 'J5812', 'B0100', 'B0101', 'B0102', 'A2610', 'A2611', 'A2612', 'A1520', 'A1720', 'A1820', 'A1920', 'A2120', 'A2320', 'A2321', 'A2322', 'A2323', 'J5611', 'J1821', 'J1822', 'A2420', 'A2520', 'A2620', 'A0130', 'A0131', 'A0330', 'A0530', 'A0630', 'A0730', 'A0930', 'A1130', 'A1230', 'J1121', 'J1122', 'J0821', 'J0822', 'J0721', 'J0722', 'J5311', 'A1330', 'A1530', 'A1730', 'A1930', 'A2130', 'A2330', 'A2530', 'A2531', 'J2220', 'J2221', 'J2222', 'J2420', 'J2520', 'J2620', 'J2621', 'J2622', 'J2720', 'J2721', 'J2722', 'J2820']

In [96]:
df['Assigned Locations'] = list

In [97]:
df

,Unnamed: 0,ID,IN_TIME,REF_ID,CON_NUM,CON_SIZE,STATUS,Out_Time,Assigned Locations
0,0,322,14-03-22 15:46:44,ALO11887,SPRE0057868,20,L,2021-06-24 17:02:53,J0000
1,1,322,14-03-22 15:46:44,ALO11887,ANKJ1447873,20,L,2021-06-24 17:02:53,J0001
2,2,322,14-03-22 15:46:44,ALO11887,ACLU3053768,20,L,2021-06-24 17:02:53,J0002
3,3,326,17-04-22 04:41:42,DP02MAR10,BUDE0578181,40,L,2021-08-26 01:41:04,J0200
4,4,326,17-04-22 04:41:42,DP02MAR10,UPDU1678037,20,E,2021-08-23 18:32:42,A0000
...,...,...,...,...,...,...,...,...,...
345,345,554,20-03-22 14:48:13,ALO11980-98997-330244,IVIP5581378,20,L,2021-07-05 16:25:51,J2622
346,346,555,20-03-22 14:48:13,ALO11980-98998-330245,XEFF1829672,20,L,2021-07-05 16:25:51,J2720
347,347,556,20-03-22 14:48:13,ALO11980-98999-330246,BFIU2996554,20,L,2021-07-05 16:25:51,J2721
348,348,557,20-03-22 14:48:13,ALO11980-99000-330247,RDCW7179253,20,L,2021-07-05 16:25:51,J2722
349,349,558,20-03-22 14:48:13,ALO11980-99001-330248,NUDE0749531,20,L,2021-07-05 16:25:51,J2820

In [98]:
df.drop(columns='Unnamed: 0',axis=1,inplace=True)

In [100]:
df.drop(columns='REF_ID',axis=1,inplace=True)
df.drop(columns='ID',axis=1,inplace=True)
df.drop(columns='STATUS',axis=1,inplace=True)

In [101]:
df

,IN_TIME,CON_NUM,CON_SIZE,Out_Time,Assigned Locations
0,14-03-22 15:46:44,SPRE0057868,20,2021-06-24 17:02:53,J0000
1,14-03-22 15:46:44,ANKJ1447873,20,2021-06-24 17:02:53,J0001
2,14-03-22 15:46:44,ACLU3053768,20,2021-06-24 17:02:53,J0002
3,17-04-22 04:41:42,BUDE0578181,40,2021-08-26 01:41:04,J0200
4,17-04-22 04:41:42,UPDU1678037,20,2021-08-23 18:32:42,A0000
...,...,...,...,...,...
345,20-03-22 14:48:13,IVIP5581378,20,2021-07-05 16:25:51,J2622
346,20-03-22 14:48:13,XEFF1829672,20,2021-07-05 16:25:51,J2720
347,20-03-22 14:48:13,BFIU2996554,20,2021-07-05 16:25:51,J2721
348,20-03-22 14:48:13,RDCW7179253,20,2021-07-05 16:25:51,J2722
349,20-03-22 14:48:13,NUDE0749531,20,2021-07-05 16:25:51,J2820

In [102]:
df.to_csv('Final Result')